repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^src/.*\.(cc|hpp)$
      - id: end-of-file-fixer
        files: ^src/.*\.(cc|hpp)$

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: ^src/.*\.(cc|hpp)$
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        files: ^src/.*\.(cc|hpp)$
