name: Release Draft

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake -B build -- VERBOSE=1

      - name: Archive
        run: |
          tar -czvf ${{ github.ref_name }}.tar.gz --transform 's,^,frogger/,' \
            src \
            CMakeLists.txt \
            LICENSE \
            README.md

      - name: Draft
        uses: actions/create-release@v1
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Source Code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: ${{ github.ref_name }}.tar.gz
          asset_name: ${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft.outputs.upload_url }}
          asset_path: build/${{ github.ref_name }}
          asset_name: ${{ github.ref_name }}
          asset_content_type: application/octet-stream